export const AdminCoursesData = [
  {
    id: 1,
    sideTitle: 'Courses',
    title: 'Data Science',
    status: 'On Going',
    instructor: 'John Doe',
    level: '3',
    startDate: {
      postedDay: 'Sunday',
      postedDate: 'May 14th',
      postedTime: '12:00 PM',
    },
    publishedOn: {
      postedDay: 'Tuesday',
      postedDate: 'July 31st',
      postedTime: '11:59 PM',
    },
  },
  {
    id: 2,
    sideTitle: 'Courses',
    title: 'Machine Learning Fundamentals',
    status: 'On Going',
    instructor: 'Jane Smith',
    level: '2',
    startDate: {
      postedDay: 'Wednesday',
      postedDate: 'September 19th',
      postedTime: '12:00 PM',
    },
    publishedOn: {
      postedDay: 'Sunday',
      postedDate: 'September 30th',
      postedTime: '11:59 PM',
    },
  },
  {
    id: 3,
    sideTitle: 'Courses',
    title: 'Web Development Bootcamp',
    status: 'Upcoming',
    instructor: 'Alex Johnson',
    level: '2',
    startDate: {
      postedDay: 'Friday',
      postedDate: 'November 9th',
      postedTime: '12:00 PM',
    },
    publishedOn: {
      postedDay: 'Friday',
      postedDate: 'November 30th',
      postedTime: '11:59 PM',
    },
  },
  {
    id: 4,
    sideTitle: 'Courses',
    title: 'UI/UX Design Principles',
    status: 'Ended',
    instructor: 'Emily Brown',
    level: '2',
    startDate: {
      postedDay: 'Friday',
      postedDate: 'May 31st',
      postedTime: '12:00 PM',
    },
    publishedOn: {
      postedDay: 'Monday',
      postedDate: 'July 30th',
      postedTime: '11:59 PM',
    },
  },
  {
    id: 5,
    sideTitle: 'Courses',
    title: 'Cloud Computing Basics',
    status: 'Upcoming',
    instructor: 'Mark Wilson',
    level: '1',
    startDate: {
      postedDay: 'Sunday',
      postedDate: 'October 14th',
      postedTime: '12:00 PM',
    },
    publishedOn: {
      postedDay: 'Wednesday',
      postedDate: 'October 31st',
      postedTime: '11:59 PM',
    },
  },
  {
    id: 6,
    sideTitle: 'Courses',
    title: 'JavaScript Advanced Techniques',
    status: 'On Going',
    instructor: 'Sophia Davis',
    level: '3',
    startDate: {
      postedDay: 'Sunday',
      postedDate: 'June 30th',
      postedTime: '12:00 PM',
    },
    publishedOn: {
      postedDay: 'Wednesday',
      postedDate: 'August 14th',
      postedTime: '11:59 PM',
    },
  },
  {
    id: 7,
    sideTitle: 'Courses',
    title: 'Python for Data Analysis',
    status: 'Ended',
    instructor: 'William Clark',
    level: '3',
    startDate: {
      postedDay: 'Tuesday',
      postedDate: 'September 4th',
      postedTime: '12:00 PM',
    },
    publishedOn: {
      postedDay: 'Monday',
      postedDate: 'September 30th',
      postedTime: '11:59 PM',
    },
  },
  {
    id: 8,
    sideTitle: 'Courses',
    title: 'Cybersecurity Essentials',
    status: 'Upcoming',
    instructor: 'Ethan Turner',
    level: '2',
    startDate: {
      postedDay: 'Friday',
      postedDate: 'November 30th',
      postedTime: '12:00 PM',
    },
    publishedOn: {
      postedDay: 'Tuesday',
      postedDate: 'December 31st',
      postedTime: '11:59 PM',
    },
  },
];
