export const AdminJobData = [
	{	
		title:'Jobs',
		company: "Here's the company name",
		position: "Here's the position",
		status: 'Open',
		postedDay: 'Monday',
		postedDate: 'June 5th',
		postedTime: '12:30 PM',
		applications: 27,
		field: 'IT & Technology',
	},
	{
		title:'Jobs',
		company: "Here's the company name",
		position: "Here's the position",
		status: 'Open',
		postedDay: 'Monday',
		postedDate: 'June 5th',
		postedTime: '12:30 PM',
		applications: 8,
		field: 'IT & Technology',
	},
	{
		title:'Jobs',
		company: "Here's the company name",
		position: "Here's the position",
		status: 'Close',
		postedDay: 'Monday',
		postedDate: 'June 5th',
		postedTime: '12:30 PM',
		applications: 15,
		field: 'IT & Technology',
	},

	{
		title:'Jobs',
		company: "Here's the company name",
		position: "Here's the position",
		status: 'Close',
		postedDay: 'Monday',
		postedDate: 'June 5th',
		postedTime: '12:30 PM',
		applications: 32,
		field: 'IT & Technology',
	},
	{
		title:'Jobs',
		company: "Here's the company name",
		position: "Here's the position",
		status: 'Close',
		postedDay: 'Monday',
		postedDate: 'June 5th',
		postedTime: '12:30 PM',
		applications: 6,
		field: 'IT & Technology',
	},
	{
		title:'Jobs',
		company: "Here's the company name",
		position: "Here's the position",
		status: 'Close',
		postedDay: 'Monday',
		postedDate: 'June 5th',
		postedTime: '12:30 PM',
		applications: 3,
		field: 'IT & Technology',
	},
];
